NAME = car

HEADER = Car.hpp Engine.hpp Transmission.hpp Steering.hpp BrakeController.hpp 

SRC = main.cpp Car.cpp Engine.cpp Transmission.cpp Steering.cpp BrakeController.cpp

OBJ = $(SRC:.cpp=.o)

CC = c++

CXXFLAGES = -Wall -Wextra -Werror -std=c++98

%.o: %.cpp
	$(CC) $(CXXFLAGES) -c $< -o $@


$(NAME) : $(OBJ) $(HEADER)
			$(CC) $(CXXFLAGES) $(SRC) -o $(NAME)

all: $(NAME)

clean:
	rm -rf $(OBJ)

fclean: clean
	rm -rf $(NAME)

re : fclean all

.PHONY: all clean fclean re